name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore GameStore.API.csproj

      - name: Build project
        run: dotnet build GameStore.API.csproj --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t gamestoreapi:ci .